language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

before_install:
  - phpenv config-rm xdebug.ini # speed up composer and tests
  - composer self-update # Composer only updated in containers ever month or so

install:
  - composer install --no-interaction

script:
  - phpunit