language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

# Composer only updated in containers ever month or so
before_install:
  - composer self-update

install:
  - composer install --no-interaction

script:
  - phpunit